# Generated by Django 4.2.5 on 2023-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='some_course_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительное поле из курса'),
        ),
        migrations.AddField(
            model_name='payment',
            name='some_lesson_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительное поле из урока'),
        ),
    ]
